jonbhanson/flutter_native_splash

CHANGELOG.md
README.md
lib/android.dart
lib/constants.dart
lib/templates.dart
pubspec.yaml

Before the plugins set the status bar color to white. As a consequence, it overrides the status bar color defined by the material swatches.
I looked in the Flutter source code to look for how they generate the material color swatch used the same principles to generate the material color dark for every color

Fixed the statusBar color

---

CHANGELOG.md
lib/flutter_native_splash.dart
pubspec.yaml

Add `toString()` to `color` settings key, avoiding type exception when uses a hex collor only with numbers like `211915 (#211915)`.
In example below, `collor` assumes an int type and will crash with type exception:
```yaml
flutter_native_splash:
image: assets/png/startup_splash.png
color: 211915
fill: true
```

Prevent unhandler int exception in color argument

---

lib/android.dart

The dividers in Android are incorrect and therefore produce overly large images on phones with pixel densities less than xxxhdpi.
They were set to:
mdpi: 2.0
hdpi: 1.8
xhdpi: 1.4
xxhdpi: 1.2
xxxhdpi: 1.0
This can be reproduced with any size image, but for example I used a 1152x300 image which looked fine on xxxhdpi, but where you could only see the middle of the image on an mdpi phone.
The values should be:
mdpi: 4.0
hdpi: 2.67
xhdpi: 2.0
xxhdpi: 1.33
xxxhdpi: 1.0
This fix makes those changes.

Fix Android dividers

---

README.md
bin/create.dart
bin/remove.dart
lib/flutter_native_splash.dart
pubspec.yaml

- Pass "--path=path/to/file.yaml" , i.e 
```
flutter pub run flutter_native_splash:create --path=path/to/file.yaml
```
- If no path specified, still goes to current defaults 
- Used args.dart as a simple way to parse args to configFile function
- Feature Request on https://github.com/jonbhanson/flutter_native_splash/issues/160
Tested with branch by updating pubspec.yaml to 
```
flutter_native_splash:
git: 
url: https://github.com/lyledean1/flutter_native_splash
ref: add-flavour
```

Add Command Line Path To Config File

---

README.md
lib/android.dart
lib/cli_commands.dart

- Add behaviour to choose between using the App's default icon or the provided splash screen image.
- Documentation for new property
Fixes #293

feat: choose between icon and image on android 12 splash

---

lib/android.dart

First of all hi, and thanks for creating and maintaining this package!
I noticed the the XML value for the branding setup was missing for API 31 (Android 12).
It was just a matter of setting it up with the same processor and using the `branding` drawable already created.
Hope this is OK, if you have any questions and/or feedback please feel free to let me know. :)

- fixed an issue where the brading path for Android 12

---

lib/ios.dart

The latest release `2.1.2` throws an unhandled Exception when trying to delete a non existent `BrandingImage.imageset` directory.
See the screenshot below with the output of the CLI:

Fix unhandled exception when branding not set

---

lib/android.dart

It was only generated in case darkColor was set.

Fix androidV31StylesXml not being generated when darkBackgroundImage is set

---

CHANGELOG.md
README.md
example/pubspec.lock
lib/cli_commands.dart
lib/templates.dart
lib/web.dart
pubspec.yaml

- Branding image support for web platform
- Updated dependencies like `flutter_lints`
- Added HTML, CSS and JS template for branding image
- Creates different pixel ratio branding images in the directory `web/splash/img/`
Resolves #385

Branding Image support for the web platform

---

lib/android.dart
lib/ios.dart
lib/web.dart

Add bottom blank line

---

lib/templates.dart

Double quotes not closed properly for src link in branding image

FIX: branding image source link broken

---

lib/templates.dart

- Using optional chaining operator instead of `if` conditions
Wouldn't benefit much, but easy to read

REFACTOR: optimized code with optional chaining operator

---

example/pubspec.lock
lib/cli_commands.dart
lib/templates.dart
lib/web.dart
pubspec.yaml

- Using `html` package to read _index.html_ file as a document tree
- Modifying content using document methods
- Writing document back to _index.html_ file
- Easy to understand code
- Would still work if _index.html_ file is edited by user
- Cleaner code

REFACTOR: Using html parser to update index.html file

---

lib/cli_commands.dart
lib/ios.dart
lib/web.dart

This PR fixes the support for the already supported image formats by the underlying library.
The existing logic of copying the background image has been changed to convert it to PNG and only copy it if it is already ".png".
https://github.com/brendan-duncan/image#supported-image-formats
> - PNG / Animated APNG
> - JPEG
> - Targa
> - GIF / Animated GIF
> - ICO
> - BMP

Fix generation for already supported image formats

---

README.md

As per the documentation, it is said to include a fix for the notification bar for iOS devices to show it when the app launches. As per vs code suggestion, setEnabledSystemUIOverlays' is deprecated and shouldn't be used. Migrate to setEnabledSystemUIMode. This feature was deprecated after v2.3.0-17.0.pre. so it might be better to migrate and have users use the newer type. 
idk about additional files that may need this change. Please have a look.

migrate to systemUIMode in readme

---

example/pubspec.lock
lib/templates.dart
lib/web.dart
pubspec.yaml

Added animated GIF support for branding, splash and background images on _web_.
<details><summary>Test Configuration Details</summary>
<details><summary>Images</summary>
| Main | Background | Branding |
|--------|--------|--------|
| ![loading-hand](https://user-images.githubusercontent.com/74326345/236673657-ab11ac6c-b7cc-489c-a813-421c67760e4f.gif) | ![splash-bg](https://user-images.githubusercontent.com/74326345/236673725-8a43aabb-69c6-4179-84e4-ea8a5720b774.png) | ![branding](https://user-images.githubusercontent.com/74326345/236673740-450a6139-c342-4dac-9113-676ae6fc4606.png) | 
</details> 
<details><summary>Config Code</summary>
```yaml
flutter_native_splash:
background_image: "assets/splash-images/splash-bg.png"
image: assets/splash-images/loading-hand.gif
branding: …
```

feat: support for GIFs in splash screen for web

---

lib/ios.dart

Using `XmlElement.innerText` instead of the deprecated `XmlElement.text`.
Tested that `text` should be replaced by `innerText` and not the `value` one.

fix: replaced deprecated code with suggested ones

---

lib/constants.dart
lib/templates.dart
lib/web.dart

Adds the splash screen related `css` and `js` code in html _head_ tag as **_inline_** instead of using `script:src` and `link:stylesheet`.
Automatically migrates previously set `script:src` and `link:stylesheet` code to inline.
closes #500

perf: using inline css & js in index.html to decrease load time

---

README.md
example/README.md
example/pubspec.yaml
lib/flutter_native_splash.dart
lib/flutter_native_splash_web.dart

Changed all the occurrences of ```flutter pub run``` which is deprecated to ```dart run```

Replaced deprecated 'flutter pub run' with 'dart run'

---

lib/flavor_helper.dart

Do not expose the extension used for the package.
If you're not careful, you could use it in your code and make it dependent on the package.

fix: Don't expose string extension

---

lib/cli_commands.dart

- When provided invalid configuration in YAML for flutter_native_splash and ran `dart run flutter_native_splash:create` command, process exits with 0 code. This indicates process completed successfully without any issue.
- With this PR, the process exits with error code to indicate the command failed to get executed.
🐞 This PR fixes #656 .
---

fix: exit process with error code when unexpected config provided in YAML

---

ios/Resources/PrivacyInfo.xcprivacy
ios/flutter_native_splash.podspec

Add PrivacyInfo to podspec of  flutter_native_splash.
I think flutter_native_splash doesn't collect anything, so I created an empty file.
See: https://github.com/flutter/flutter/issues/139761#issuecomment-1881394943

Add iOS privacy manifests

---

README.md
lib/android.dart
lib/cli_commands.dart
lib/ios.dart
lib/templates.dart

- Support adding bottom padding for branding image regarding this issue https://github.com/jonbhanson/flutter_native_splash/issues/694
1. follow this documentation to run and generate the native splash screen
2. enable branding image
3. add this config on your config yaml
```yaml
branding_bottom_padding: 24
#branding_bottom_padding_ios: 24 #specific config for iOS
#branding_bottom_padding_android: 24 #specific config for Android
```
5. observe the branding image position

feat: support adjust padding bottom for branding image

---

README.md

This documentation enhancement clarifies how to combine Android gravity flags for splash screen layouts, specifically addressing the common need to simultaneously fill and crop splash screen images. While this functionality exists in the underlying Android implementation, making it explicit in the Flutter documentation will help developers achieve better splash screen presentations without having to dive into platform-specific details:
> android_gravity can be combined using the | operator to achieve multiple effects. For example: android_gravity: fill|clip_vertical - This will fill the width while maintaining the image's vertical aspect ratio
This documentation update addresses a critical aspect of splash screen behavior on Android tablets, particularly devices like Amazon Fire tablets …

Readme Update - Combining Effects with android_gravity
